 redIADS = SkynetIADS:create('Enemy IADS')
 redIADS:addSAMSitesByPrefix('RSA')
 redIADS:addEarlyWarningRadarsByPrefix('REW')
 local RedcommandCenter = StaticObject.getByName("RedSquare")
 local comRPowerSource = StaticObject.getByName("RedSquarePower")
 redIADS:addCommandCenter(RedcommandCenter):addPowerSource(comRPowerSource)
 redIADS:activate()
 
 blueIADS = SkynetIADS:create('Friendly IADS')
 blueIADS:addSAMSitesByPrefix('BSA')
 blueIADS:addEarlyWarningRadarsByPrefix('BEW')
 local BluecommandCenter = StaticObject.getByName("Hague")
 local comBPowerSource = StaticObject.getByName("HaguePower")
 blueIADS:addCommandCenter(BluecommandCenter):addPowerSource(comBPowerSource)
 blueIADS:activate()